name: 解压文件到指定文件夹并提交

on:
  workflow_dispatch: # 手动触发工作流
    inputs:
      file_path:
        description: '要解压的文件路径'
        required: true
      destination_folder:
        description: '要解压到的目标文件夹名称 (例如: script)'
        required: true

permissions:
  contents: write

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置解压目标路径
        id: set_destination
        run: |
          echo "DESTINATION_PATH=${{ github.event.inputs.destination_folder }}" >> $GITHUB_ENV
          echo "解压目标文件夹: ${{ env.DESTINATION_PATH }}"

      - name: 解压 ZIP 文件到指定文件夹
        if: endsWith(github.event.inputs.file_path, '.zip')
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          unzip "${{ github.event.inputs.file_path }}" -d "$DESTINATION_PATH"
          echo "成功解压 ZIP 文件到: $DESTINATION_PATH"

      - name: 解压 TAR/TAR.GZ/TAR.BZ2 文件到指定文件夹
        if: ${{ !endsWith(github.event.inputs.file_path, '.zip') }}
        run: |
          if [[ "${{ github.event.inputs.file_path }}" == *.tar ]]; then
            mkdir -p "$DESTINATION_PATH"
            tar -xf "${{ github.event.inputs.file_path }}" -C "$DESTINATION_PATH"
            echo "成功解压 TAR 文件到: $DESTINATION_PATH"
          elif [[ "${{ github.event.inputs.file_path }}" == *.tar.gz || "${{ github.event.inputs.file_path }}" == *.tgz ]]; then
            mkdir -p "$DESTINATION_PATH"
            tar -xzf "${{ github.event.inputs.file_path }}" -C "$DESTINATION_PATH"
            echo "成功解压 TAR.GZ 文件到: $DESTINATION_PATH"
          elif [[ "${{ github.event.inputs.file_path }}" == *.tar.bz2 || "${{ github.event.inputs.file_path }}" == *.tbz2 ]]; then
            mkdir -p "$DESTINATION_PATH"
            tar -xjf "${{ github.event.inputs.file_path }}" -C "$DESTINATION_PATH"
            echo "成功解压 TAR.BZ2 文件到: $DESTINATION_PATH"
          else:
            echo "不支持的文件格式: ${{ github.event.inputs.file_path }}"
            exit 1
          fi

      - name: 添加并提交更改
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add "$DESTINATION_PATH"
          git commit -m "Add解压后的文件到 ${{ env.DESTINATION_PATH }}"
          echo "Commit successful"

      - name: 推送更改
        run: |
          git push origin HEAD:${{ github.ref_name }}
          echo "Push successful"
